# Basic Python

## 1. Split this string

In [1]:
s = "Hi there Sam!"
x=s.split()
print(x)

['Hi', 'there', 'Sam!']


*`italicized text`*## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [2]:
planet = "Earth"
diameter = 12742
print ('the diameter of {} is {} kilometers'.format (planet,diameter))

the diameter of Earth is 12742 kilometers


## 3. In this nest dictionary grab the word "hello"

In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [4]:
d={'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
print(d['k1'][3]["tricky"][3]['target'][3])   

hello


In [ ]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [5]:
import numpy as np
arr = [0 for element in range (10)]
print(arr)


[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


In [10]:
import numpy as np
arr = [5for element in range (10)]
print(arr)


[5, 5, 5, 5, 5, 5, 5, 5, 5, 5]


## 5. Create an array of all the even integers from 20 to 35

In [14]:
import numpy as np 
array=np.arange(20,35,2)
print("Array of all three even integers from 20 to 35")
print(arr)

Array of all three even integers from 20 to 35
[5, 5, 5, 5, 5, 5, 5, 5, 5, 5]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [16]:
z=np.arange(9).reshape(3,3)
print(z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [22]:
a=np.array([1,2,3])
b=np.array([4,5,6])
con=np.concatenate((a,b),axis=0)
print(con)

[1 2 3 4 5 6]


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [17]:
import pandas as pd
data=[['tom',88],[nick',20],['juli',87]]
df=pd.DataFrame(data, columns=['name','age'])                  
df

name  age
0   tom   88
1  nick   20
2  juli   87

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [19]:
import datetime
start=datetime.date(2023,1,1)
k=41
res=[]
for day in range(k):
    date=(start+datetime.timedelta(days=day)).isoformat()
    res.append(date)
print("next k dates lists:"+str(res))    

next k dates lists:['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04', '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08', '2023-01-09', '2023-01-10', '2023-01-11', '2023-01-12', '2023-01-13', '2023-01-14', '2023-01-15', '2023-01-16', '2023-01-17', '2023-01-18', '2023-01-19', '2023-01-20', '2023-01-21', '2023-01-22', '2023-01-23', '2023-01-24', '2023-01-25', '2023-01-26', '2023-01-27', '2023-01-28', '2023-01-29', '2023-01-30', '2023-01-31', '2023-02-01', '2023-02-02', '2023-02-03', '2023-02-04', '2023-02-05', '2023-02-06', '2023-02-07', '2023-02-08', '2023-02-09', '2023-02-10']


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [ ]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [ ]:
import pandas as pd
lists = [[1,'aaa',22], [2,'bbb',25],[3,'ccc',24]]
df=pd.DataFrame(lists,columns=['category','name','marks'])
print(df)

   category name  marks
0         1  aaa     22
1         2  bbb     25
2         3  ccc     24
